KILL: {

	* = * "KILL"
	Colour:	
			* = * "-Colour Map"
			
			.fill 15, 0
			.byte BLUE, BLACK, BLACK, BLUE, BLUE, BLACK, ORANGE, LIGHT_RED, BLACK, BLACK, RED, BLACK, BLACK
			.fill 15, 0
			.byte BLUE, BLACK, BLACK, BLUE, BLUE, BLACK, ORANGE, LIGHT_RED, BLACK, BLACK, RED, BLACK, BLACK
			.fill 15, 0
			.byte YELLOW, BLUE, BLACK, BLUE, BLUE, WHITE, BLUE, BLACK, BLACK, WHITE, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte YELLOW, BLUE, BLACK, BLUE, BLUE, WHITE, BLUE, BLACK, BLACK, LIGHT_RED, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, BLACK, ORANGE, YELLOW, BLUE, WHITE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, BLACK, ORANGE, YELLOW, BLUE, WHITE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, BLUE, ORANGE, BLACK, BLUE, BLUE, BLUE, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte BLUE, BLUE, ORANGE, BLACK, BLUE, BLUE, BLUE, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, ORANGE, YELLOW, BLACK, BLUE, BLUE, BLUE, BLACK, BLACK, RED, RED, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, ORANGE, YELLOW, BLACK, BLUE, BLUE, BLUE, BLACK, BLACK, RED, RED, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, ORANGE, YELLOW, WHITE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, ORANGE, YELLOW, WHITE, BLUE, BLUE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, ORANGE, YELLOW, BLACK, BLUE, ORANGE, BLUE, LIGHT_RED, BLACK, BLACK, BLACK, BLACK, BLUE
			.fill 15, 0
			.byte YELLOW, ORANGE, BLACK, BLACK, BLUE, ORANGE, BLUE, LIGHT_RED, BLACK, BLACK, BLACK, BLUE, BLUE
			.fill 15, 0
			.byte ORANGE, BLACK, LIGHT_RED, ORANGE, BLACK, ORANGE, BLUE, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK
			.fill 15, 0
			.byte ORANGE, BLACK, LIGHT_RED, ORANGE, BLACK, ORANGE, BLUE, BLACK, BLACK, BLACK, BLACK, BLUE, BLACK
			.fill 15, 0
			.byte YELLOW, ORANGE, BLACK, WHITE, BLACK, BLUE, ORANGE, RED, BLACK, BLACK, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte YELLOW, ORANGE, LIGHT_RED, WHITE, BLACK, BLUE, ORANGE, RED, BLACK, BLACK, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, BLACK, RED, BLUE, BLUE, BLACK, ORANGE, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, ORANGE, RED, BLUE, BLUE, BLACK, ORANGE, BLACK, BLUE, BLACK, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte ORANGE, BLACK, BLACK, BLUE, BLACK, BLUE, BLUE, WHITE, GREEN, WHITE, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte ORANGE, BLACK, BLACK, BLUE, BLACK, BLUE, BLUE, RED, GREEN, WHITE, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, BLACK, WHITE, BLUE, BLACK, BLUE, BLUE, ORANGE, BLUE, RED, BLACK, BLACK, YELLOW
			.fill 15, 0
			.byte BLACK, BLACK, RED, BLUE, BLUE, BLUE, BLUE, ORANGE, BLUE, RED, BLACK, BLACK, YELLOW
			.fill 15, 0
			.byte BLACK, BLACK, BLACK, BLUE, GREEN, BLUE, BLUE, BLUE, BLUE, BLACK, RED, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, BLACK, BLACK, BLUE, GREEN, BLUE, BLUE, BLUE, BLUE, BLACK, RED, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, BLACK, BLACK, BLUE, BLACK, BLUE, ORANGE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, BLACK, BLACK, BLUE, BLACK, BLUE, ORANGE, BLUE, BLACK, BLACK, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, LIGHT_RED, BLACK, BLUE, BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, YELLOW, BLACK
			.fill 15, 0
			.byte BLACK, LIGHT_RED, BLACK, BLUE, BLUE, BLACK, BLACK, BLUE, BLACK, BLACK, BLACK, YELLOW, BLACK
			.fill 15, 0
			.byte BLACK, BLACK, LIGHT_RED, YELLOW, BLUE, BLUE, BLACK, ORANGE, BLUE, LIGHT_RED, BLACK, BLACK, BLACK
			.fill 15, 0
			.byte BLACK, BLACK, LIGHT_RED, YELLOW, BLUE, BLUE, BLACK, ORANGE, BLUE, LIGHT_RED, BLACK, BLACK, BLACK












}