//#import "lookups/charData.asm"
#import "lookups/labels.asm"
#import "lookups/vic.asm"
#import "lookups/registers.asm"
// #import "interrupts/irq.asm"
// #import "setup/macros.asm"
// #import "setup/maploader.asm"
// #import "setup/titleloader.asm"
// #import "setup/insloader.asm"
// #import "setup/sound.asm"
// #import "lookups/levelData.asm"
// #import "interrupts/score.asm"
// #import "interrupts/lives.asm"
// #import "interrupts/charDrawing.asm"
// #import "interrupts/caveman.asm"
// #import "interrupts/egg.asm"
// #import "interrupts/cave.asm"
// #import "interrupts/bird.asm"
// #import "interrupts/axe.asm"
// #import "interrupts/lava.asm"
// #import "interrupts/dino.asm"
// #import "interrupts/volcano.asm"
// #import "interrupts/stars.asm"

